# fleet-ui activated by systemd socket
# see https://developer.atlassian.com/blog/2015/03/docker-systemd-socket-activation/
        - name: fleet-ui.socket
          command: start
          enable: true
          content: |
              [Unit]
              Description=Socket for Fleet-ui
              
              [Socket]
              ListenStream=3333
              Service=fleet-ui-proxy.service
              BindIPv6Only=both
              
              [Install] 
              WantedBy=sockets.target
              WantedBy=fleet-ui-proxy.service
        - name: fleet-ui-proxy.service
          command: start
          content: |
              [Unit]
              Description=Fleet-ui Proxy
              Requires=fleet-ui.service
              After=fleet-ui.service
              
              [Service]
              ExecStart=/lib/systemd/systemd-socket-proxyd 127.0.0.1:3000
        - name: fleet-ui.service
          command: start
          content: |
              [Unit]
              Description=fleet-ui
              Requires=docker.service
              After=docker.service
              
              [Service]
              EnvironmentFile=/var/lib/apps/fleet-ui/envvars
              TimeoutStartSec=20min
              ExecStartPre=-/usr/bin/docker rm %n
              ExecStartPre=/var/lib/apps/bin/dkpull xuwang/fleet-ui
              ExecStart=/usr/bin/docker run --rm --name %n -p 3000:3000 \
                  -v /home/core/.ssh/id_rsa_fleetui:/root/id_rsa \
                  xuwang/fleet-ui
              ExecStartPost=/var/lib/apps/bin/waitport 127.0.0.1 3000
              ExecStop=-/usr/bin/docker stop %n
              