[template]
prefix = "haproxy-discover"
keys = [
  "http-services",
  "tcp-services"
]
src    = "haproxy.tmpl"
dest   = "/var/lib/apps-data/haproxy/haproxy.cfg"

# Check engerated {{.src}}. The check returns 2 because of "no-listeners" even though the format is valid. Grep the Configuration file has no error to get return 0
check_cmd = "docker run -v /var/lib/apps-data/haproxy/certs:/etc/ssl/private  --rm -v /var/lib/apps-data/haproxy/{{.src}}:/tmp/haproxy.cfg xuwang/haproxy-supervisor haproxy -f /tmp/haproxy.cfg -c | grep 'Configuration file has no error'"

# Graceful reload haproxy; 
reload_cmd = "container=$(docker ps | grep -Eo 'haproxy-[[:digit:]].service'); if [ ! -z $container ]; then docker exec $container entrypoint.sh restart; fi"
