concurrent = 1

[[runners]]
  name = "runner-01"
  url = "https://gitlab.docker.local:8443/ci"
  token = "667c131c919b3b6f653f12e3b2f032"
  tls-ca-file = ""
  executor = "docker"
  [runners.docker]
    image = "ruby:2.1"
    privileged = false
    volumes = ["/cache"]
