concurrent = 1

[[runners]]
  name = "Dind Runner"
  url = "https://gitlab.docker.local:8443/ci"
  token = "20a6bf832be557b53728918d7dc4f5"
  tls-ca-file = ""
  executor = "docker"
  environment = ["DOCKER_DAEMON_ARGS=--insecure-registry registry.docker.local"]
  [runners.docker]
    image = "gitlab/dind:latest"
    privileged = true
    volumes = ["/cache"]
    wait_for_services_timeout=300
